services:
  postgres-catalog:
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 987234
    volumes:
      - ./postgres-catalog:/var/lib/postgresql/data
      - ./create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    networks:
      - leaf-love-laugh-network
    expose:
      - 5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5

  postgres-users:
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 987234
    volumes:
      - ./postgres-users:/var/lib/postgresql/data
      - ./create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    networks:
      - leaf-love-laugh-network
    expose:
      - 5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5

  cassandra-search:
    container_name: cassandra-search
    networks:
      - leaf-love-laugh-network
    expose:
      - 9042
    image: cassandra:latest
    healthcheck:
      test: [ "CMD-SHELL", "cqlsh -e 'DESCRIBE KEYSPACES;'" ]
      interval: 30s
      timeout: 10s
      retries: 5

  cassandra-review:
    container_name: cassandra-review
    networks:
      - leaf-love-laugh-network
    expose:
      - 9042
    image: cassandra:latest
    healthcheck:
      test: [ "CMD-SHELL", "cqlsh -e 'DESCRIBE KEYSPACES;'" ]
      interval: 30s
      timeout: 10s
      retries: 5

  cassandra-latest:
    container_name: cassandra-latest
    networks:
      - leaf-love-laugh-network
    expose:
      - 9042
    image: cassandra:latest
    healthcheck:
      test: [ "CMD-SHELL", "cqlsh -e 'DESCRIBE KEYSPACES;'" ]
      interval: 30s
      timeout: 10s
      retries: 5

  zookeeper-server:
    image: bitnami/zookeeper:latest
    container_name: zookeeper-server
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - leaf-love-laugh-network

  kafka-server:
    container_name: kafka-server
    networks:
      - leaf-love-laugh-network
    image: 'bitnami/kafka:latest'
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-server:2181

  kafka-topics:
    image: bitnami/kafka:latest
    command: kafka-topics.sh --create --bootstrap-server kafka-server:9092 --replication-factor 1 --partitions 3 --topic reviews
    networks:
      - leaf-love-laugh-network
    depends_on:
      - kafka-server

  create-tables:
    container_name: create-tables
    networks:
      - leaf-love-laugh-network
    image: create-tables
    pull_policy: build
    build:
      context: .
      dockerfile: dockerfiles/create-tables.Dockerfile
    depends_on:
      cassandra-search:
        condition: service_healthy
      cassandra-latest:
        condition: service_healthy
      cassandra-review:
        condition: service_healthy
      postgres-catalog:
        condition: service_healthy
      postgres-users:
        condition: service_healthy

  populate-postgres:
    container_name: populate-postgres
    networks:
      - leaf-love-laugh-network
    image: populate-postgres
    pull_policy: build
    build:
      context: .
      dockerfile: dockerfiles/populate-postgres.Dockerfile
    depends_on:
      create-tables:
        condition: service_completed_successfully

  populate-cassandra:
    container_name: populate-cassandra
    networks:
      - leaf-love-laugh-network
    image: populate-cassandra
    pull_policy: build
    build:
      context: .
      dockerfile: dockerfiles/populate-cassandra.Dockerfile
    depends_on:
      create-tables:
        condition: service_completed_successfully

  lll-api:
    container_name: lll-api
    networks:
      - leaf-love-laugh-network
    image: lll-api
    pull_policy: build
    ports:
      - 8080:8080
    build:
      context: .
      dockerfile: dockerfiles/facade.Dockerfile
    depends_on:
      lll-authentication:
        condition: service_started
      lll-catalog:
        condition: service_started
      lll-latest:
        condition: service_started
      lll-review:
        condition: service_started
      lll-search:
        condition: service_started

  lll-search:
    container_name: lll-search
    networks:
      - leaf-love-laugh-network
    image: lll-search
    pull_policy: build
    expose:
      - 8080
    build:
      context: .
      dockerfile: dockerfiles/search.Dockerfile
    depends_on:
      populate-cassandra:
        condition: service_completed_successfully

  lll-authentication:
    container_name: lll-authentication
    networks:
      - leaf-love-laugh-network
    image: lll-authentication
    pull_policy: build
    expose:
      - 8080
    build:
      context: .
      dockerfile: dockerfiles/authentication.Dockerfile
    depends_on:
      postgres-users:
        condition: service_started
      cassandra-latest:
        condition: service_healthy

  lll-catalog:
    container_name: lll-catalog
    networks:
      - leaf-love-laugh-network
    image: lll-catalog
    pull_policy: build
    expose:
      - 8080
    build:
      context: .
      dockerfile: dockerfiles/catalog.Dockerfile
    depends_on:
      populate-postgres:
        condition: service_completed_successfully

  lll-review:
    container_name: lll-review
    networks:
      - leaf-love-laugh-network
    image: lll-review
    pull_policy: build
    expose:
      - 8080
    build:
      context: .
      dockerfile: dockerfiles/review.Dockerfile
    depends_on:
      populate-cassandra:
        condition: service_completed_successfully

  lll-latest:
    container_name: lll-latest
    networks:
      - leaf-love-laugh-network
    image: lll-latest
    pull_policy: build
    expose:
      - 8080
    build:
      context: .
      dockerfile: dockerfiles/latest.Dockerfile
    depends_on:
      populate-cassandra:
        condition: service_completed_successfully

networks:
  leaf-love-laugh-network:
    name: leaf-love-laugh-network
